services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BookLending
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
    ports:
      - "8080:80"
    environment:
        - ASPNETCORE_URLS=http://+:8
    
volumes:
  pgdata:
